package com.rk.tables.dao;

import javax.sql.DataSource;

import org.springframework.beans.factory.InitializingBean;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.jdbc.core.JdbcTemplate;

public class CRTablesDao implements InitializingBean {

	@Autowired
	DataSource dataSource;

	private JdbcTemplate jdbcTemplateObject;

	public final static String CREATE_COURSE_TABLE = "CREATE TABLE IF NOT EXISTS COURSE "
			+ "( CID INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 100, INCREMENT BY 1) PRIMARY KEY, "
			+ " CNAME VARCHAR(30) , " + " CWEEKNAME  VARCHAR(50) ," + " CTIME  VARCHAR(5) , " + " CCREDITS INTEGER ) ";

	public final static String CREATE_STUDENT_TABLE = "CREATE TABLE IF NOT EXISTS STUDENT "
			+ "( SID INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 500, INCREMENT BY 1) PRIMARY KEY, "
			+ " SNAME VARCHAR(30) , " + " SEMAIL  VARCHAR(50) )";

	public final static String CREATE_COURSE_REG_TABLE = "CREATE TABLE IF NOT EXISTS COURSE_REG (SID INTEGER, CID INTEGER,"
			+ "CONSTRAINT FK_COURSEREG1 FOREIGN KEY (SID) REFERENCES STUDENT(SID),"
			+ " CONSTRAINT FK_COURSEREG2 FOREIGN KEY (CID) REFERENCES COURSE(CID))";

	@Override
	public void afterPropertiesSet() throws Exception {

		jdbcTemplateObject = new JdbcTemplate(dataSource);

		jdbcTemplateObject.execute(CREATE_COURSE_TABLE);
		jdbcTemplateObject.execute(CREATE_STUDENT_TABLE);
		jdbcTemplateObject.execute(CREATE_COURSE_REG_TABLE);
		// jdbcTemplateObject.execute("SHUTDOWN");
	
		System.out.println("***********************Table Created***********");
		/*
		 * String SQL =
		 * "insert into course (CNAME,CWEEKNAME,CTIME,CCREDITS) values(?,?,?,?)"
		 * ; Calendar calendar = Calendar.getInstance(); java.sql.Timestamp
		 * ourJavaTimestampObject = new
		 * java.sql.Timestamp(calendar.getTime().getTime());
		 * 
		 * jdbcTemplateObject = new JdbcTemplate(dataSource);
		 * jdbcTemplateObject.update(SQL,"fn","weekName",ourJavaTimestampObject,
		 * 2);
		 * 
		 * System.out.println("****************Data Inserted*************");
		 */
	}

}
